-- Tạo database
CREATE DATABASE HotelDb;
GO

USE HotelDb;
GO

-- Bảng LOAIPHONG
CREATE TABLE LOAIPHONG (
    LoaiPhongID INT IDENTITY(1,1) PRIMARY KEY,
    TenLoai NVARCHAR(50) NOT NULL,
    DonGiaNgay DECIMAL(18,0) NOT NULL,
    DonGiaGio DECIMAL(18,0) NOT NULL,
    GhiChu NVARCHAR(200) NULL
);

-- Bảng PHONG
CREATE TABLE PHONG (
    PhongID INT IDENTITY(1,1) PRIMARY KEY,
    MaPhong NVARCHAR(20) NOT NULL UNIQUE,
    LoaiPhongID INT NOT NULL,
    TrangThai INT NOT NULL DEFAULT 0,
    GhiChu NVARCHAR(200) NULL,
    CONSTRAINT FK_PHONG_LOAIPHONG FOREIGN KEY (LoaiPhongID) REFERENCES LOAIPHONG(LoaiPhongID)
);

-- Bảng KHACHHANG
CREATE TABLE KHACHHANG (
    KhachHangID INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    CCCD NVARCHAR(20) NOT NULL,
    HinhCCCD VARBINARY(MAX) NULL,
    DienThoai NVARCHAR(20),
    DiaChi NVARCHAR(200)
);

-- Bảng DATPHONG
CREATE TABLE DATPHONG (
    DatPhongID INT IDENTITY(1,1) PRIMARY KEY,
    KhachHangID INT NOT NULL,
    PhongID INT NOT NULL,
    NgayDen DATETIME NOT NULL,
    NgayDiDuKien DATETIME NOT NULL,
    NgayDiThucTe DATETIME NULL,
    TrangThai INT NOT NULL DEFAULT 0,
    TienCoc DECIMAL(18,0) NOT NULL DEFAULT 0,
    CONSTRAINT FK_DATPHONG_KHACHHANG FOREIGN KEY (KhachHangID) REFERENCES KHACHHANG(KhachHangID),
    CONSTRAINT FK_DATPHONG_PHONG FOREIGN KEY (PhongID) REFERENCES PHONG(PhongID)
);

-- Bảng DICHVU
CREATE TABLE DICHVU (
    DichVuID INT IDENTITY(1,1) PRIMARY KEY,
    TenDichVu NVARCHAR(100) NOT NULL,
    DonGia DECIMAL(18,0) NOT NULL
);

-- Bảng CHITIETDICHVU
CREATE TABLE CHITIETDICHVU (
    ChiTietDichVuID INT IDENTITY(1,1) PRIMARY KEY,
    DatPhongID INT NOT NULL,
    DichVuID INT NOT NULL,
    SoLuong INT NOT NULL,
    CONSTRAINT FK_CTDV_DATPHONG FOREIGN KEY (DatPhongID) REFERENCES DATPHONG(DatPhongID),
    CONSTRAINT FK_CTDV_DICHVU FOREIGN KEY (DichVuID) REFERENCES DICHVU(DichVuID)
);

-- Bảng HOADON
CREATE TABLE HOADON (
    HoaDonID INT IDENTITY(1,1) PRIMARY KEY,
    DatPhongID INT NOT NULL,
    NgayLap DATETIME NOT NULL DEFAULT GETDATE(),
    TongTien DECIMAL(18,0) NOT NULL,
    DaThanhToan BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_HOADON_DATPHONG FOREIGN KEY (DatPhongID) REFERENCES DATPHONG(DatPhongID)
);

-- Bảng USERS
CREATE TABLE USERS (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    [Password] NVARCHAR(200) NOT NULL,
    [Role] NVARCHAR(20) NOT NULL
);

-- Dữ liệu mẫu
INSERT INTO LOAIPHONG (TenLoai, DonGiaNgay, DonGiaGio, GhiChu)
VALUES (N'Phòng đơn', 300000, 50000, NULL),
       (N'Phòng đôi', 500000, 80000, NULL);

INSERT INTO PHONG (MaPhong, LoaiPhongID, TrangThai)
VALUES (N'101', 1, 0),
       (N'102', 1, 0),
       (N'201', 2, 0);

INSERT INTO USERS (Username, [Password], [Role])
VALUES ('admin', '123456', 'Admin'),
       ('letan', '123456', 'Letan');
