-- Hotel Management legacy migration
-- Date: 2026-02-21
-- MySQL 5.7+/8.0+

START TRANSACTION;

-- 1) Add BookingType to DATPHONG (1=Hourly, 2=Overnight)
SET @has_booking_type := (
    SELECT COUNT(1)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
      AND TABLE_NAME = 'DATPHONG'
      AND COLUMN_NAME = 'BookingType'
);
SET @sql := IF(
    @has_booking_type = 0,
    'ALTER TABLE DATPHONG ADD COLUMN BookingType TINYINT NOT NULL DEFAULT 2',
    'ALTER TABLE DATPHONG MODIFY COLUMN BookingType TINYINT NOT NULL DEFAULT 2'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 2) Room type pricing defaults
CREATE TABLE IF NOT EXISTS LOAIPHONG (
    LoaiPhongID INT NOT NULL,
    TenLoaiPhong VARCHAR(120) NULL,
    DonGiaNgay DECIMAL(18,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (LoaiPhongID)
);

INSERT INTO LOAIPHONG (LoaiPhongID, TenLoaiPhong, DonGiaNgay)
VALUES
    (1, 'Phòng đơn', 200000),
    (2, 'Phòng đôi', 300000)
ON DUPLICATE KEY UPDATE
    TenLoaiPhong = VALUES(TenLoaiPhong),
    DonGiaNgay = VALUES(DonGiaNgay);

-- 3) STAY_INFO (1-1 with booking)
CREATE TABLE IF NOT EXISTS STAY_INFO (
    StayInfoID INT NOT NULL AUTO_INCREMENT,
    DatPhongID INT NOT NULL,
    LyDoLuuTru VARCHAR(120) NULL,
    GioiTinh VARCHAR(40) NULL,
    NgaySinh DATE NULL,
    LoaiGiayTo VARCHAR(80) NULL,
    SoGiayTo VARCHAR(60) NULL,
    QuocTich VARCHAR(80) NULL,
    NoiCuTru VARCHAR(40) NULL,
    LaDiaBanCu TINYINT(1) NOT NULL DEFAULT 0,
    MaTinhMoi VARCHAR(16) NULL,
    MaXaMoi VARCHAR(16) NULL,
    MaTinhCu VARCHAR(16) NULL,
    MaHuyenCu VARCHAR(16) NULL,
    MaXaCu VARCHAR(16) NULL,
    DiaChiChiTiet VARCHAR(255) NULL,
    GiaPhong DECIMAL(18,2) NOT NULL DEFAULT 0,
    SoDemLuuTru INT NOT NULL DEFAULT 1,
    GuestListJson LONGTEXT NULL,
    CreatedAtUtc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAtUtc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy VARCHAR(80) NULL,
    UpdatedBy VARCHAR(80) NULL,
    PRIMARY KEY (StayInfoID),
    UNIQUE KEY UX_STAY_INFO_BOOKING (DatPhongID)
);

-- 4) BOOKING_EXTRAS (extras lines)
CREATE TABLE IF NOT EXISTS BOOKING_EXTRAS (
    BookingExtraID INT NOT NULL AUTO_INCREMENT,
    DatPhongID INT NOT NULL,
    ItemCode VARCHAR(32) NOT NULL,
    ItemName VARCHAR(120) NOT NULL,
    Qty INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Note VARCHAR(255) NULL,
    CreatedAtUtc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAtUtc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy VARCHAR(80) NULL,
    UpdatedBy VARCHAR(80) NULL,
    PRIMARY KEY (BookingExtraID),
    UNIQUE KEY UX_BOOKING_EXTRAS_CODE (DatPhongID, ItemCode)
);

-- 5) Optional one-time BookingType backfill heuristic
UPDATE DATPHONG
SET BookingType = CASE
                    WHEN DATE(COALESCE(NgayDiThucTe, NgayDiDuKien, NgayDen)) = DATE(NgayDen)
                         AND TIMESTAMPDIFF(HOUR, NgayDen, COALESCE(NgayDiThucTe, NgayDiDuKien, NgayDen)) < 10
                      THEN 1
                    ELSE 2
                  END
WHERE COALESCE(DataStatus, 'active') <> 'deleted'
  AND (
        BookingType IS NULL
        OR BookingType NOT IN (1, 2)
        OR (
            BookingType = 2
            AND DATE(COALESCE(NgayDiThucTe, NgayDiDuKien, NgayDen)) = DATE(NgayDen)
            AND TIMESTAMPDIFF(HOUR, NgayDen, COALESCE(NgayDiThucTe, NgayDiDuKien, NgayDen)) < 10
        )
      );

-- 6) Indexes for statistics/explorer/date-range + paging
SET @sql := IF(
    (SELECT COUNT(1) FROM INFORMATION_SCHEMA.STATISTICS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'DATPHONG' AND INDEX_NAME = 'IDX_DATPHONG_DATERANGE_TYPE_STATUS_ID') = 0,
    'CREATE INDEX IDX_DATPHONG_DATERANGE_TYPE_STATUS_ID ON DATPHONG (NgayDen, BookingType, TrangThai, DatPhongID)',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(1) FROM INFORMATION_SCHEMA.STATISTICS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'DATPHONG' AND INDEX_NAME = 'IDX_DATPHONG_TYPE_DATE_ID') = 0,
    'CREATE INDEX IDX_DATPHONG_TYPE_DATE_ID ON DATPHONG (BookingType, NgayDen, DatPhongID)',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(1) FROM INFORMATION_SCHEMA.STATISTICS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'DATPHONG' AND INDEX_NAME = 'IDX_DATPHONG_PHONG_STATUS_ID') = 0,
    'CREATE INDEX IDX_DATPHONG_PHONG_STATUS_ID ON DATPHONG (PhongID, TrangThai, DatPhongID)',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(1) FROM INFORMATION_SCHEMA.STATISTICS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'HOADON' AND INDEX_NAME = 'IDX_HOADON_BOOKING_DATE') = 0,
    'CREATE INDEX IDX_HOADON_BOOKING_DATE ON HOADON (DatPhongID, NgayLap)',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(1) FROM INFORMATION_SCHEMA.STATISTICS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'BOOKING_EXTRAS' AND INDEX_NAME = 'IDX_BOOKING_EXTRAS_BOOKING') = 0,
    'CREATE INDEX IDX_BOOKING_EXTRAS_BOOKING ON BOOKING_EXTRAS (DatPhongID)',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql := IF(
    (SELECT COUNT(1) FROM INFORMATION_SCHEMA.STATISTICS
      WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'BOOKING_EXTRAS' AND INDEX_NAME = 'IDX_BOOKING_EXTRAS_BOOKING_AMOUNT') = 0,
    'CREATE INDEX IDX_BOOKING_EXTRAS_BOOKING_AMOUNT ON BOOKING_EXTRAS (DatPhongID, Amount)',
    'SELECT 1'
);
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

COMMIT;
